FROM openjdk:8-jdk

ENV test_suite="XXXX"
ENV test_environment="XXXX"
# ENV protractor_config="protractor-docker.config.js"
ENV chrome_version=89.0.4389.128-1

# Node.js
RUN curl -sL https://deb.nodesource.com/setup_15.x | bash - \
	&& apt-get install -y nodejs \
	&& rm -rf /var/lib/apt/lists/* /var/cache/apt/*

# Google Chrome
RUN wget -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
	&& echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list \
	&& apt-get update -qqy
# Google Chrome
RUN wget -O /tmp/google-chrome-stable.deb https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${chrome_version}_amd64.deb \
	&& apt install -y /tmp/google-chrome-stable.deb \
	&& rm /tmp/google-chrome-stable.deb \
	&& sed -i 's/"$HERE\/chrome"/"$HERE\/chrome" --no-sandbox/g' /opt/google/chrome/google-chrome

# Set the working directory as Project
WORKDIR /Project